# https://github.com/binhex/arch-sonarr
services:
  sonarr:
    image: binhex/arch-sonarr:latest
    container_name: sonarr
    restart: always
    healthcheck:
      test: curl --connect-timeout 15 --max-time 100 --silent --show-error --fail "http://localhost:8989" > /dev/null
      interval: 1m
      timeout: 30s
      retries: 3
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - $DOWNLOADS_LOCATION:/downloads
      - $MEDIA_LOCATION:/media
    ports:
      - 8989:8989
      - 9897:9897
    networks:
      - proxy
networks:
  proxy:
    external: true