# https://hub.docker.com/r/uroni/urbackup-server
services:
  urbackup:
    image: uroni/urbackup-server:latest
    container_name: urbackup
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/var/urbackup
      - ./log:/var/log
      - $BACKUPS_LOCATION:/backups
    ports:
      - 55413-55415:55413-55415
      - 35623:35623/udp
    networks:
      - proxy
networks:
  proxy:
    external: true