# https://github.com/binhex/arch-readarr
services:
  readarr:
    image: binhex/arch-readarr:latest
    container_name: readarr
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --max-time 100 --silent --show-error --fail "http://localhost:8787" > /dev/null
      interval: 1m
      timeout: 30s
      retries: 3
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - $DATA_LOCATION:/data
    ports:
      - 8787:8787
    networks:
      - proxy
networks:
  proxy:
    external: true