# https://github.com/binhex/arch-prowlarr
services:
  prowlarr:
    image: binhex/arch-prowlarr:latest
    container_name: prowlarr
    restart: always
    healthcheck:
      test: curl --connect-timeout 15 --max-time 100 --silent --show-error --fail "http://localhost:9696" > /dev/null
      interval: 1m
      timeout: 30s
      retries: 3
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config/prowlarr
    ports:
      - 9696:9696
    networks:
      - proxy
networks:
  proxy:
    external: true