# https://gotify.net/docs/install
services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: curl --connect-timeout 15 --max-time 100 --silent --show-error --fail "http://localhost:80" > /dev/null
      interval: 1m
      timeout: 30s
      retries: 3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/app/data
    ports:
      - 8090:80
    networks:
      - proxy
networks:
  proxy:
    external: true