# https://gethomepage.dev/latest/installation/docker/
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    # - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/app/config
      - ./images:/app/public/images
      - ./icons:/app/public/icons
    ports:
      - 3002:3000
    networks:
      - proxy
networks:
  proxy:
    external: true