# https://crazymax.dev/diun/install/docker/
services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      # DIUN Configuration
      - DIUN_WATCH_WORKERS=$DIUN_WATCH_WORKERS
      - DIUN_WATCH_SCHEDULE=$DIUN_WATCH_SCHEDULE
      - DIUN_WATCH_JITTER=$DIUN_WATCH_JITTER
      - DIUN_WATCH_FIRSTCHECKNOTIF=$DIUN_WATCH_FIRSTCHECKNOTIF
      - DIUN_WATCH_RUNONSTARTUP=$DIUN_WATCH_RUNONSTARTUP
      # DIUN Docker provider
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      # DIUN Gotify notifications
      - DIUN_NOTIF_GOTIFY_ENDPOINT=$DIUN_NOTIF_GOTIFY_ENDPOINT
      - DIUN_NOTIF_GOTIFY_TOKEN=$DIUN_NOTIF_GOTIFY_TOKEN
      - DIUN_NOTIF_GOTIFY_PRIORITY=$DIUN_NOTIF_GOTIFY_PRIORITY
      - DIUN_NOTIF_GOTIFY_TIMEOUT=$DIUN_NOTIF_GOTIFY_TIMEOUT
      - DIUN_NOTIF_GOTIFY_TEMPLATETITLE=$DIUN_NOTIF_GOTIFY_TEMPLATETITLE
      - DIUN_NOTIF_GOTIFY_TEMPLATEBODY=$DIUN_NOTIF_GOTIFY_TEMPLATEBODY
      # DIUN Discord notifications
      - DIUN_NOTIF_DISCORD_WEBHOOKURL=$DIUN_NOTIF_DISCORD_WEBHOOKURL
      - DIUN_NOTIF_DISCORD_MENTIONS=$DIUN_NOTIF_DISCORD_MENTIONS
      - DIUN_NOTIF_DISCORD_RENDERFIELDS=$DIUN_NOTIF_DISCORD_RENDERFIELDS
      - DIUN_NOTIF_DISCORD_TIMEOUT=$DIUN_NOTIF_DISCORD_TIMEOUT
      - DIUN_NOTIF_DISCORD_TEMPLATEBODY=$DIUN_NOTIF_DISCORD_TEMPLATEBODY
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    networks:
      - proxy
networks:
  proxy:
    external: true