# https://crazymax.dev/diun/install/docker/
services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    networks:
      - proxy
networks:
  proxy:
    external: true