# https://homarr.dev/docs/getting-started/installation/
services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /etc/localtime:/etc/localtime:ro
    # - /var/run/docker.sock:/var/run/docker.sock
      - ./configs:/app/data/configs
      - ./icons:/app/public/icons
      - ./data:/data
    ports:
      - 7575:7575
    networks:
      - proxy
networks:
  proxy:
    external: true