# https://docs.linuxserver.io/images/docker-grocy
services:
  grocy:
    image: linuxserver/grocy:latest
    container_name: grocy
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --max-time 100 --silent --show-error --fail "http://localhost:80" > /dev/null
      interval: 1m
      timeout: 30s
      retries: 3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
    ports:
      - 9283:80
    networks:
      - proxy
networks:
  proxy:
    external: true