# https://docs.firefly-iii.org/how-to/firefly-iii/installation/docker/
services:
  firefly:
    image: fireflyiii/core:latest
    container_name: firefly
    restart: unless-stopped
    depends_on:
      - firefly-db
    env_file: .env
    volumes:
      - ./upload:/var/www/html/storage/upload
    ports:
      - '8083:8080'
    networks:
      - proxy
  firefly-db:
    image: mariadb:lts
    container_name: firefly-db
    restart: unless-stopped
    env_file: .db.env
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - proxy
  firefly-cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    container_name: firefly-cron
    restart: unless-stopped
    command: sh -c "echo \"0 3 * * * wget -qO- http://firefly:8080/api/v1/cron/Z57yEfWLKD8TXbCM2uvJVFGDJjZcPum6\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - proxy
networks:
  proxy:
    external: true
