# https://github.com/binhex/arch-delugevpn
services:
  deluge:
    image: binhex/arch-delugevpn:latest
    container_name: deluge
    restart: always
    privileged: true
    sysctls:
      - "net.ipv4.conf.all.src_valid_mark=1"
    healthcheck:
      test: curl --connect-timeout 15 --max-time 100 --silent --show-error --fail "http://localhost:8112" > /dev/null
      interval: 1m
      timeout: 30s
      retries: 3
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - $DOWNLOADS_LOCATION:/downloads
    ports:
      - 8112:8112
      - 8118:8118
      - 58846:58846
    networks:
      - proxy
networks:
  proxy:
    external: true