# https://github.com/binhex/arch-lidarr
services:
  lidarr:
    image: binhex/arch-lidarr:latest
    container_name: lidarr
    restart: always
    healthcheck:
      test: curl --connect-timeout 15 --max-time 100 --silent --show-error --fail "http://localhost:8686" > /dev/null
      interval: 1m
      timeout: 30s
      retries: 3
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - $DOWNLOADS_LOCATION:/downloads
      - $MEDIA_LOCATION:/media
    ports:
      - 8686:8686
    networks:
      - proxy
networks:
  proxy:
    external: true