# https://docs.linuxserver.io/images/docker-wikijs/
services:
  wikijs:
    image: linuxserver/wikijs:latest
    container_name: wikijs
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --max-time 100 --silent --show-error --fail "http://localhost:3000" > /dev/null
      interval: 1m
      timeout: 30s
      retries: 3
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./data:/data
    ports:
      - 3015:3000
    networks:
      - proxy
networks:
  proxy:
    external: true