# https://github.com/FlareSolverr/FlareSolverr
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:pr-1282
    container_name: flaresolverr
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8191:8191
    networks:
      - proxy
networks:
  proxy:
    external: true